### ISSUE TITLE
Compatibility Login not documented

### ISSUE THREAD

**Issue by 111andre111** [OctagonMobile/Octagon-Analytics#22]
Hi folks,

would you mind to document please, that this implementation is based on OpenDistro Elasticsearch Login implementation?
https://github.com/OctagonMobile/Octagon-Analytics#prerequisites

Thank you.

**Comment by rameezhandel** [comment]
@111andre111 , Documentation updated!!!
https://github.com/OctagonMobile/Octagon-Analytics#prerequisites
